config/routes.rb
Rails.application.routes.draw do
  devise_for :clients

  root 'home#index'

  resources :chats, only: [:new, :create, :show, :index]

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_and_belongs_to_many :clients
  has_many :messages, dependent: :destroy

  def clients_except(client)
    companions_of(client).select(:email)
  end

  def companions_of(client)
    clients.where.not(id: client)
  end
end

app/models/client.rb
class Client < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum role: { trainer: 0, user: 1 }

  has_and_belongs_to_many :chats, dependent: :nullify
  has_many :messages, dependent: :nullify

  validates :role, presence: true

  scope :chatting_with,
        -> (client) { joins(:chats).where(chats: {id: client.chats.pluck(:id)}).distinct }

  scope :not_chatting_with,
        -> (client) { where.not(id: chatting_with(client).pluck(:id)) }

  class << self
    def can_start_chat_with(client)
      not_chatting_with(client).where.not(id: client.id).select(:id, :email, :role)
    end
  end

  def name
    email.split('@')[0]
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :client
  belongs_to :chat

  validates :body, presence: true, length: { minimum: 2, maximum: 1000 }

  after_create_commit { MessageBroadcastJob.perform_later(self) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :role
    end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate_client!

  def index
    @chats = current_client.chats.all
  end

  def new
    @chat_creator = ChatCreator.new
  end

  def create
    @chat_creator = ChatCreator.new(chat_params)
    render 'new' and return unless @chat_creator.valid?

    chat = nil

    begin
      Chat.transaction do
        chat = Chat.create!(
          clients: [current_client, Client.find_by_id(@chat_creator.client_id)]
        )
        chat.messages.create!(body: @chat_creator.body, client: current_client)
      end

      redirect_to chat_path(chat)
    rescue => e
      render 'new'
    end
  end

  def show
    @chat = current_client.chats.find(params[:id])
    @messages = @chat.messages
    @message = Message.new
  end

  private

  def chat_params
    params.require(:chat_creator).permit(:client_id, :body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if client_signed_in?
      @trainers_counter = Client.trainer.count
      @users_counter = Client.user.count

      @last_trainer = Client.trainer.order(:id).last
      @last_user = Client.user.order(:id).last
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, opts = {})
    opts[:alt] = user.name
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}?s=#{opts.delete(:size) { 40 }}",
              opts
  end

  def format_time(time)
    time.strftime('%H:%M %d %B') if ((Time.now - 3.days).beginning_of_day .. (Time.now + 3.days).end_of_day).include?(time)
    time.strftime('%d %B') if (Time.now.beginning_of_year .. Time.now.end_of_year).include?(time)
    time.strftime('%d %B %Y')
  end

  def client_collector_array(clients)
    clients.map { |c| [ "#{c.name} (#{c.role.humanize})", c.id] }
  end

  def clients_names(clients)
    clients.map(&:name).join(', ')
  end
end

app/views/chats/_message.slim
.card
  .card-block
    .row
      .col-md-1
        = gravatar_for message.client
      .col-md-11
        p.card-text
          span.text-muted
            = "#{message.client.name} at #{format_time(message.created_at)} says"
            br
          = message.body

app/views/chats/index.slim
.text-center
  = link_to 'New chat', new_chat_path, class: 'btn btn-success'
.row
  - @chats.each do |chat|
    .col-md-6
      = link_to chat_path(chat) do
        = clients_names(chat.clients_except(current_client))
        br
        = format_time chat.created_at

app/views/chats/new.slim
= simple_form_for @chat_creator, url: chats_path, method: :post do |f|
  = f.input :client_id, as: :select, collection: client_collector_array(Client.can_start_chat_with(current_client)), include_blank: false
  = f.input :body
  = f.submit 'Start chat', class: 'btn btn-default'

app/views/chats/show.slim
h3 = "Chat with: #{clients_names(@chat.clients_except(current_client))}"
br
div id="messages" data-chat-id=@chat.id
  = render partial: 'chats/message', collection: @messages

hr

= form_for @message, url: '#' do |f|
  = hidden_field_tag 'chat_id', @chat.id
  .form-group
    = f.text_area :body, class: 'form-control'
    small.text-muted From 2 to 1000 characters

  = f.submit "Post", class: 'btn btn-primary btn-lg'

app/views/home/index.slim
- if current_client
  .text-center
    = link_to 'Chat', chats_path, class: 'btn btn-default'
  br
  .row
    .col-md-6
      .thumbnail
        = "Registred: #{pluralize(@trainers_counter, 'trainer')}"
        - if @last_trainer.present?
          hr
          .last-trainer
            p = "Last trainer: #{@last_trainer.name}"
            p = "Created: #{format_time @last_trainer.created_at}"
    .col-md-6
      .thumbnail
        = "Registred: #{pluralize(@users_counter, 'user')}"
        - if @last_user.present?
          hr
          .last-trainer
          p = "Last trainer: #{@last_user.name}"
          p = "Created: #{format_time @last_user.created_at}"
- else
  p.lead.text-center = 'You have to sign in if you want to get access to app'

app/views/layouts/application.slim
doctype html
html lang="en"

  head
    title Trainers & Users Chat
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    = render 'shared/navigation'
    .container
      = yield

app/views/shared/_navigation.slim
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
      = link_to 'Trainers & Users Chat', root_path, class: 'navbar-brand'

      ul.nav.navbar-nav.pull-right
        - unless client_signed_in?
          li = link_to 'Sign In', new_client_session_path, class: 'nav-link'
          li = link_to 'Sign Up', new_client_registration_path, class: 'nav-link'

        - else
          li.navbar-nav
            span.text-muted
              = 'Logged in as '
              strong = current_client.name
          li.nav-item.active
            = link_to 'Log out', destroy_client_session_path, method: :delete, class: 'nav-link'